name: my_loop_partner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0
  auto_route: ^7.8.4
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  google_fonts: ^6.1.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.6
  json_serializable: ^6.7.1
  custom_lint: ^0.5.7
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
